In [ ]:
import pandas as pd
import numpy as np

from datetime import datetime

In [50]:
# Declare Variable
today = pd.Timestamp(datetime.today())

In [58]:
# Read CSV
books_df = pd.read_csv(r"../data/03_Library Systembook.csv")

# Standardise column headers
books_df.columns = books_df.columns.str.title()

# Drops NaN records
books_df = books_df.dropna(subset=['Id', 'Books'])

# Convert Id fields to integers
for col in ['Id', 'Customer Id']:
    books_df[col] = books_df[col].astype(int)

# Capitalisew book titles
books_df['Books'] = books_df['Books'].str.title()

# Standardise dates
for col in ['Book Checkout', 'Book Returned']:
    books_df[col] = pd.to_datetime(books_df[col].str.strip('"'), format = '%d/%m/%Y', errors='coerce')

# Date validation

date_checks = [
    books_df['Book Checkout'].isna() | books_df['Book Returned'].isna(),
    (books_df['Book Checkout'] > today) | (books_df['Book Returned'] > today),
    books_df['Book Checkout'] > books_df['Book Returned']
]

date_flags = [
    'Invalid Dates',
    'Future Dates',
    'Checked Prceeding Return'
]

books_df['Date Validity'] = np.select(date_checks, date_flags, default='Valid Date')

books_df['Checkout Duration'] = np.where(
    books_df['Date Validity'] == 'Valid Date',
    (books_df['Book Returned'] - books_df['Book Checkout']).dt.days,
    None
)

display(books_df)

,Id,Books,Book Checkout,Book Returned,Days Allowed To Borrow,Customer Id,Date Validity,Checkout Duration
0,1,Catcher In The Rye,2023-02-20,2023-02-25,2 weeks,1,Valid Date,5.0
1,2,Lord Of The Rings The Two Towers,2023-03-24,2023-03-21,2 weeks,2,Checked Prceeding Return,None
2,3,Lord Of The Rings The Return Of The Kind,2023-03-29,2023-03-25,2 weeks,3,Checked Prceeding Return,None
3,4,The Hobbit,2023-04-02,2023-03-25,2 weeks,4,Checked Prceeding Return,None
4,5,Dune,2023-04-02,2023-03-25,2 weeks,5,Checked Prceeding Return,None
5,6,Little Women,2023-04-02,2023-05-01,2 weeks,1,Valid Date,29.0
6,7,It,2063-04-10,2023-04-03,2 weeks,6,Future Dates,None
7,8,Misery,2023-04-15,2023-04-03,2 weeks,7,Checked Prceeding Return,None
8,9,Catch 22,2023-04-15,2023-04-16,2 weeks,7,Valid Date,1.0
9,10,Animal Farm,2023-04-20,2023-04-24,2 weeks,2,Valid Date,4.0
10,11,1984,2023-04-23,2023-04-27,2 weeks,8,Valid Date,4.0
11,12,Little Women,2023-04-02,2023-05-01,2 weeks,1,Valid Date,29.0
12,13,East Of Eden,2023-04-30,2023-05-05,2 weeks,2,Valid Date,5.0
13,14,America Is In The Heart,2023-05-01,2023-05-07,2 weeks,3,Valid Date,6.0
14,15,Wuthering Heights,2023-05-01,2023-05-10,2 weeks,9,Valid Date,9.0
15,16,Dark Tales,2023-05-15,2023-06-01,2 weeks,2,Valid Date,17.0
16,17,The Bloody Chamber,NaT,2023-06-04,2 weeks,3,Invalid Dates,None
17,18,Les Miserables,2023-06-03,2023-06-07,2 weeks,5,Valid Date,4.0
18,19,Dracula,2023-06-10,2023-07-10,2 weeks,10,Valid Date,30.0
19,20,Frankenstein,2023-06-01,2023-06-20,2 weeks,2,Valid Date,19.0

In [48]:
books_df = pd.read_csv(r"../data/03_Library Systembook.csv")

#Standardise column headers
books_df.columns = books_df.columns.str.title()

# Drops NaN records
books_df = books_df.dropna(subset=['Id', 'Books'])

# Convert Id fields to integers
for col in ['Id', 'Customer Id']:
    books_df[col] = books_df[col].astype(int)

# Capitalisew book titles
books_df['Books'] = books_df['Books'].str.title()

# Standardise dates
for col in ['Book Checkout', 'Book Returned']:
    books_df[col] = pd.to_datetime(books_df[col].str.strip('"'), format = '%d/%m/%Y', errors='coerce')

# Date validation

date_checks = [
    books_df['Book Checkout'].isna() & books_df['Book Returned'].isna(),
    books_df['Book Checkout'] > datetime.today() | books_df['Book Returned'] > datetime.today(),
    books_df['Book Checkout'] > books_df['Book Returned']
]

date_flags = [
    'Invalid Dates',
    'Future Dates',
    'Checked Prceeding Return'
]

books_df['Date Validity'] = np.select(date_checks, date_flags, default='Valid Date')

books_df['Checkout Duration'] = np.where(
    books_df['Date Validity'] == 'Valid Date',
    books_df['Book Returned'] - books_df['Book Checkout'],
    None
)

display(books_df)

TypeError: unsupported operand type(s) for |: 'datetime.datetime' and 'DatetimeArray'

In [37]:
customers_df = pd.read_csv(r"../data/03_Library SystemCustomers.csv")

# Drops NaN records
customers_df = customers_df.dropna()

customers_df['Customer ID'] = customers_df['Customer ID'].astype(int)

# Standardise capitalisation
customers_df['Customer Name'] = customers_df['Customer Name'].str.title()

display(customers_df)

   Customer ID     Customer Name
0            1          Jane Doe
1            2        John Smith
2            3        Dan Reeves
4            5    William Holden
5            6     Jaztyn Forest
6            7     Jackie Irving
7            8  Matthew Stirling
8            9         Emory Ted